debug: false

server:
  port: 8081

# actuator
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
        show-details: always
  
spring:
  application:
    name: spring-boot-admin-client
  security:
    user:
      name: client
      password: client
  boot: 
    admin:
      client:
        url: http://localhost:8070, http://localhost:8071 # 2 serveurs admin 
        register-once: false
        auto-registration: true
        auto-deregistration: true
        #config pour se connecter au serveur
        username: server
        password: server
        instance:
          #prefer-ip: true
          service-base-url: http://localhost:${server.port} #url client
          metadata:
            # config pour que le serveur se connect au client
            user.name: ${spring.security.user.name}
            user.password: ${spring.security.user.password}
            tags : 
              datacenter : d-${server.port}